// <auto-generated />
namespace ApiSony.BO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterescolaridadesexo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterescolaridadesexo));
        
        string IMigrationMetadata.Id
        {
            get { return "201802040229595_alterescolaridadesexo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
